
class phathienR
{
public:
	void MainThread(void * lpParam);
	void Nomes();
	char * Nome_do_Main;
	char * GameGuard_Value;
	char * StartUp_Address_NewName;
	char * StartUp_Original_Name;
	char * Injected_Window_1;
	char * Injected_Window_2;
	char * Injected_Window_3;
	char * Inject_Dll_Value;
	char * GameGuard_Config_file_Value;
	char * Ten_Launcher;
	char * MainClassName;
	char * LauncherClassName;
	char * MainWindowName;
	char * Ten_Dll;
	//char * IP_Server_and_Hard;	
	//char * FTP_User;
	//char * FTP_Pass;
	//char * Ten_Dll;
	char * LauncherWindowName;
	char * Ten_Cua_So;
	char * HackSplash_WebSite;
	char * Nome;	
	char * Nome2;
	char * Serial;
	char * Version;
	char * IP;
	char * Data;

	int TAM_DUNG_TAT_CA;
	int BanSec_Update_time;
	int phathien_serial_version;
	int Virtual_Memory_Protect;
	int Check_File_Names;
	int Splash_Screen;
	int Close_ClassName;
	int Close_Window;
	int Anti_Kill_Scans;
	int Ativa_CRC_Geral;
	int CRC_Client_MRS;
	int CRC_System;
	int CRC_Codex;
	int CRC_ProtectBMP;	
	int CRC_GameGuard;
	int CRC_StartUp;
	int CRC_Inject_dll;
	int CRC_Gunz;	
	int CRC_Launcher;
	int Phathien_Inject;
	int LoadThemDLL;
	int Phathien_Dump;
	int Disable_Windows_ASLR;
	int Launcher_Check;
	int Log_Txt_Hack;
	int Message_Warning_En;
	int Phathien_Speed_Tickcount;
	int Phathien_PID;
	//int Hack_Log_Upload;
	int Memory_Buffer_P;
	int GameGuard_Exe_Protection;
	int GG_Close_Game_immediately;
	int Inject_dll_Protection;
	int Copy_exe_to_Windows_Startup;
	int Show_Windows_Window_list;
	int Test_Main_Win_Class_PID;
	int Test_Launcher_Win_Class_PID;
	int Phathien_Window;
	int Phathien_TuKhoa;
	int Phathien_TuKhoa_Win;	
	int Phathien_TuKhoa_NC; 
	int Phathien_TuKhoa_Class;
	int Phathien_Speed_Hethong;
	int Phathien_ClassName;
	//int Server_Ban;
	int Phathien_Hide_Toolz;
	//int Hardware_Ban;
	int Rebuild_Main_Data;
	//int Log_File_Size_To_upload;
	int TESTE;

	//time detectors occours
	int PHHide_Thoigian;
	int DHard_occours;
	int DBan_occours;
	int PHDump_Thoigian;	
	int DWindow_Thoigian;	
	int DClassName_Thoigian;	
	int Phathien_Inject_Thoigian;	
	int Anti_Kill_Thoigian;	
	int Phathien_Speed_Hethong_Thoigian;
	int DPID_Thoigian;	
	int Phathien_Speed_Thoigian;	
	int Phathien_TuKhoa_Thoigian;
	int Phathien_TuKhoa_Win_Thoigian;
	int Phathien_TuKhoa_NC_Thoigian;
	int Phathien_TuKhoa_Class_Thoigian;
	int Virtual_Mem_occours;
	int DVerifica_occours;
	int Launcher_Check_Thoigian;
	
	long CRC_LauncherEXE;
	long CRC_SystemMRS;
	long CRC_CodexDLL;
	long CRC_Protect;
	long CRC_GameGuard_Value;
	long CRC_Inject_dll_Value;
	long CRC_StartUp_Value;
	long CRC_GunzEXE;
	long CRC_Interface;
	long CRC_Maps;
	long CRC_MapsChallenge;
	long CRC_model;
	long CRC_Quest;
	long CRC_sfx;
	long CRC_Sound;
};
extern phathienR phathien;